openapi: 3.0.0
info:
  title: 'ChoreCash API'
  version: 1.0.0
servers:
  -
    url: 'https://krc-coding.dk/api'
    description: Production
paths:
  /api/ping:
    get:
      tags:
        - System
      summary: Ping
      description: 'Ping the system.'
      operationId: 71e5f6846cc889c8adcf33f548917ad9
      responses:
        '200':
          description: OK
        '404':
          description: 'Service not found'
        '503':
          description: 'Service unavilable'
  /api/status:
    get:
      tags:
        - System
      summary: 'System status'
      description: 'Get system status.'
      operationId: c15296e5fe3364f3cd1aceb1d737c5e6
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/status-response'
        '401':
          description: 'Access denied'
        '500':
          description: 'Internal server error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-500-response'
        '503':
          description: 'Service unavilable'
components:
  schemas:
    error-500-response:
      title: 'HTTP/500 response'
      properties:
        message:
          description: 'Error message.'
          type: string
          example: 'Unprocessable entity.'
      type: object
    status-response:
      title: 'Status response'
      properties:
        database:
          description: 'Database service status'
          type: boolean
          example: true
        api:
          description: 'API service status'
          type: boolean
          example: true
      type: object
tags:
  -
    name: System
    description: System
