openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8000'
paths:
  /api/ping:
    get:
      summary: ''
      operationId: getApiPing
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: ''
      tags:
        - Endpoints
      security: []
  /api/status:
    get:
      summary: ''
      operationId: getApiStatus
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  database: true
                  api: true
                properties:
                  database:
                    type: boolean
                    example: true
                  api:
                    type: boolean
                    example: true
      tags:
        - Endpoints
      security: []
  /api/auth/login:
    post:
      summary: ''
      operationId: postApiAuthLogin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/auth/register:
    post:
      summary: ''
      operationId: postApiAuthRegister
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  '/api/user/{user_id}':
    get:
      summary: ''
      operationId: getApiUserUser_id
      description: ''
      parameters: []
      responses:
        500:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Server Error'
                properties:
                  message:
                    type: string
                    example: 'Server Error'
      tags:
        - Endpoints
      security: []
    put:
      summary: ''
      operationId: putApiUserUser_id
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    delete:
      summary: ''
      operationId: deleteApiUserUser_id
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: user_id
        description: 'The ID of the user.'
        example: 18
        required: true
        schema:
          type: integer
  '/api/user/family/{family}/profiles':
    get:
      summary: ''
      operationId: getApiUserFamilyFamilyProfiles
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: ''
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: family
        description: 'The family.'
        example: ipsam
        required: true
        schema:
          type: string
  '/api/user/{family}/{user}/points':
    get:
      summary: ''
      operationId: getApiUserFamilyUserPoints
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: ''
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: family
        description: ''
        example: 3
        required: true
        schema:
          type: integer
      -
        in: path
        name: user
        description: ''
        example: ducimus
        required: true
        schema:
          type: string
tags:
  -
    name: Endpoints
    description: ''
